/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const seed = async function (knex) {
  await knex("food_sensitivities").del();
  await knex("food_sensitivities").insert([
    // Dairy/Egg
    { user_id: 1, category: "Dairy/Egg", food_name: "Alpha-Lactalbumin (Whey)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Dairy/Egg", food_name: "Beta-Lactalbumin (Whey)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Dairy/Egg", food_name: "Casein", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Dairy/Egg", food_name: "Egg White", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Dairy/Egg", food_name: "Egg Yolk", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Dairy/Egg", food_name: "Milk (Buffalo)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Dairy/Egg", food_name: "Milk (Cow)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Dairy/Egg", food_name: "Milk (Goat)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Dairy/Egg", food_name: "Milk (Sheep)", severity: "unassigned", created_at: knex.fn.now() },

    // Grains
    { user_id: 1, category: "Grains", food_name: "Barley", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Couscous", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Durum Wheat", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Gliadin", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Malt", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Oat", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Rye", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Spelt", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Wheat", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains", food_name: "Wheat Bran", severity: "unassigned", created_at: knex.fn.now() },

    // Grains (Gluten-Free)
    { user_id: 1, category: "Grains (Gluten-Free)", food_name: "Amaranth", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains (Gluten-Free)", food_name: "Buckwheat", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains (Gluten-Free)", food_name: "Corn", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains (Gluten-Free)", food_name: "Millet", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains (Gluten-Free)", food_name: "Polenta", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains (Gluten-Free)", food_name: "Quinoa", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains (Gluten-Free)", food_name: "Rice", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Grains (Gluten-Free)", food_name: "Tapioca", severity: "unassigned", created_at: knex.fn.now() },

    // Fruit
    { user_id: 1, category: "Fruit", food_name: "Apple", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Apricot", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Avocado", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Banana", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Black Currant", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Blackberry", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Blueberry", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Cherry", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Cranberry", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Date", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Fig", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Grape", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Grapefruit", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Guava", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Kiwi", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Lemon", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Lime", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Lychee", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Mango", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Melon (Honeydew)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Mulberry", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Nectarine", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Olive", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Orange", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Papaya", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Peach", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Pear", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Pineapple", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Plum", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Pomegranate", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Raisin", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Raspberry", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Red Currant", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Rhubarb", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Strawberry", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Tangerine", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fruit", food_name: "Watermelon", severity: "unassigned", created_at: knex.fn.now() },

    // Vegetables
    { user_id: 1, category: "Vegetables", food_name: "Artichoke", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Arugula", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Asparagus", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Beet", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Bell Peppers", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Broccoli", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Brussels Sprout", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Cabbage (Red)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Cabbage (White)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Carrot", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Cauliflower", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Celery", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Chard", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Chicory", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Cucumber", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Eggplant", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Fennel (Leaf)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Leek", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Lettuce", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Onion", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Potato", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Radish", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Shallot", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Spinach", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Squash (Butternut)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Squash (Summer)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Sweet Potato", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Tomato", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Turnip", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Watercress", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Vegetables", food_name: "Yuca", severity: "unassigned", created_at: knex.fn.now() },

    // Fish/Seafood
    { user_id: 1, category: "Fish/Seafood", food_name: "Alga Espaguette", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Alga Wakame", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Anchovy", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Barnacle", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Bass", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Carp", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Caviar", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Clam", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Cockle", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Cod", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Crab", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Cuttlefish", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Eel", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Haddock", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Hake", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Herring", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Lobster", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Mackerel", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Monkfish", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Mussel", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Octopus", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Oyster", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Perch", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Pike", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Plaice", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Razor Clam", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Salmon", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Sardine", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Scallop", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Sea Bream (Gilthead)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Sea Bream (Red)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Shrimp/Prawn", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Snail (Sea Snail)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Sole", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Spirulina", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Squid", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Swordfish", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Trout", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Tuna", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Fish/Seafood", food_name: "Turbot", severity: "unassigned", created_at: knex.fn.now() },

    // Meat
    { user_id: 1, category: "Meat", food_name: "Beef", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Chicken", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Duck", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Goat", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Horse", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Lamb", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Ostrich", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Ox", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Patridge", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Pork", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Quail", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Rabbit", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Turkey", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Veal", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Venison", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Meat", food_name: "Wild Boar", severity: "unassigned", created_at: knex.fn.now() },

    // Herbs/Spices
    { user_id: 1, category: "Herbs/Spices", food_name: "Aniseed", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Basil", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Bayleaf", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Camomile", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Cayenne", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Cinnamon", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Clove", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Coriander (Leaf)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Cumin", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Curry (Mixed Spices)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Dill", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Garlic", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Ginger", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Ginkgo", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Ginseng", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Hops", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Licorice", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Marjoram", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Mint", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Mustard Seed", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Nettle", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Nutmeg", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Parsley", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Peppercorn (Black/White)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Peppermint", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Red Chili Pepper", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Rosemary", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Saffron", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Sage", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Tarragon", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Thyme", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Herbs/Spices", food_name: "Vanilla", severity: "unassigned", created_at: knex.fn.now() },

    // Nuts/Seeds/Legumes
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Almond", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Bean (Broad)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Bean (Green)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Bean (Red Kidney)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Bean (White Haricot)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Brazil Nut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Canola", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Cashew Nut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Chestnut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Chickpea", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Coconut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Flax Seed", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Hazelnut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Lentil", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Macadamia Nut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Pea", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Peanut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Pine Nut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Pistachio", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Sesame Seed", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Soy Bean", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Sunflower Seed", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Tiger Nut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Nuts/Seeds/Legumes", food_name: "Walnut", severity: "unassigned", created_at: knex.fn.now() },

    // Miscellaneous
    { user_id: 1, category: "Miscellaneous", food_name: "Agar Agar", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Aloe Vera", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Cane Sugar", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Caper", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Carob", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Cocao Bean", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Coffee", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Cola Nut", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Honey", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Mushroom", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Tea (Black)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Tea (Green)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Transglutaminase", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Yeast (Baker's)", severity: "unassigned", created_at: knex.fn.now() },
    { user_id: 1, category: "Miscellaneous", food_name: "Yeast (Brewer's)", severity: "unassigned", created_at: knex.fn.now() }
  ]);
};
